### ISSUE TITLE
Issue while running Tracker

### ISSUE THREAD

**Issue by RahulChandrashekar17061984** [wiseman/turboshrimp-tracker#2]
Dear John,

With help of Mr.Shantanu Kumar i was able to handle dependecies...however while running the application i get the below error

Reflection warning, com/lemondronor/turboshrimp_tracker/opencv.clj:61:23 - reference to field getData on java.awt.image.DataBuffer can't be resolved.
Exception in thread "main" java.lang.ExceptionInInitializerError, compiling:(C:\Users\rac4kor\AppData\Local\Temp\form-init5431141739802643841.clj:1:109)
        at clojure.lang.Compiler.load(Compiler.java:7142)
        at clojure.lang.Compiler.loadFile(Compiler.java:7086)
        at clojure.main$load_script.invoke(main.clj:274)
        at clojure.main$init_opt.invoke(main.clj:279)
        at clojure.main$initialize.invoke(main.clj:307)
        at clojure.main$null_opt.invoke(main.clj:342)
        at clojure.main$main.doInvoke(main.clj:420)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:383)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)
Caused by: java.lang.ExceptionInInitializerError
        at nu.pattern.OpenCV$SharedLoader.getInstance(OpenCV.java:206)
        at nu.pattern.OpenCV.loadShared(OpenCV.java:156)
        at com.lemondronor.turboshrimp_tracker.opencv$init.invoke(opencv.clj:17)
        at com.lemondronor.turboshrimp_tracker$_main.doInvoke(turboshrimp_tracker.clj:385)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.Var.invoke(Var.java:375)
        at user$eval5.invoke(form-init5431141739802643841.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6703)
        at clojure.lang.Compiler.eval(Compiler.java:6693)
        at clojure.lang.Compiler.load(Compiler.java:7130)
        ... 11 more
Caused by: nu.pattern.OpenCV$UnsupportedPlatformException: Operating system "WINDOWS" and architecture "X86_64" are not supported.
        at nu.pattern.OpenCV.extractNativeBinary(OpenCV.java:324)
        at nu.pattern.OpenCV.extractNativeBinary(OpenCV.java:292)
        at nu.pattern.OpenCV.access$100(OpenCV.java:22)
        at nu.pattern.OpenCV$SharedLoader.<init>(OpenCV.java:178)
        at nu.pattern.OpenCV$SharedLoader.<init>(OpenCV.java:162)
        at nu.pattern.OpenCV$SharedLoader$Holder.<clinit>(OpenCV.java:202)
        ... 21 more

Do you have any comments on this. 

I am currently running this application in windows 7 - 64 bit.

**Comment by wiseman** [comment]
I used the [OpenCV bindings from Pattern Consulting](https://github.com/PatternConsulting/opencv), which only support Linux and OS X. If you can find OpenCV bindings that will work on Linux, OS X and Windows, I'd be happy to use them instead.
